Models/Customer.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace SchadTest.Models
{
    public class Customer
    {
        public Customer()
        {
            Invoices = new HashSet<Invoice>();
        }

        public int Id { get; set; }
        [Display(Name = "Customer Name")]
        public string CustName { get; set; } = null!;
        [Display(Name = "Address")]
        public string Adress { get; set; } = null!;
        public bool? Status { get; set; }
        [Display(Name = "Type")]
        public int CustomerTypeId { get; set; }
        [Display(Name = "Type")]
        public virtual CustomerType CustomerType { get; set; } = null!;
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}

Models/CustomerType.cs
namespace SchadTest.Models
{
    public class CustomerType
    {
        public CustomerType()
        {
            Customers = new HashSet<Customer>();
        }

        public int Id { get; set; }
        public string Description { get; set; } = null!;

        public virtual ICollection<Customer> Customers { get; set; }
    }
}

Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.EntityFrameworkCore;
using SchadTest.Data;
using SchadTest.Models;

namespace SchadTest.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Customers.Include(c => c.CustomerType);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Customers == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .Include(c => c.CustomerType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            //first add type user
            int cType = _context.CustomerTypes.Count();
            if (cType < 1) return LocalRedirect($"~/CustomerTypes/Create");

            ViewData["CustomerTypeId"] = new SelectList(_context.CustomerTypes, "Id", "Description");
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CustName,Adress,Status,CustomerTypeId")] Customer customer)
        {
            if (customer.CustName !=null && customer.Adress !=null && customer.CustomerTypeId > 0)
            {
                customer.Status = true;
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerTypeId"] = new SelectList(_context.CustomerTypes, "Id", "Description", customer.CustomerTypeId);
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Customers == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            ViewData["CustomerTypeId"] = new SelectList(_context.CustomerTypes, "Id", "Description", customer.CustomerTypeId);
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CustName,Adress,Status,CustomerTypeId")] Customer customer)
        {
            if (id != customer.Id)
            {
                return NotFound();
            }

            if (customer.CustName != null && customer.Adress != null && customer.CustomerTypeId > 0)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerTypeId"] = new SelectList(_context.CustomerTypes, "Id", "Id", customer.CustomerTypeId);
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Customers == null)
            {
                return NotFound();
            }

            var customer = await _context.Customers
                .Include(c => c.CustomerType)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Customers == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Customers'  is null.");
            }
            var customer = await _context.Customers.FindAsync(id);
            if (customer != null)
            {
                _context.Customers.Remove(customer);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
          return _context.Customers.Any(e => e.Id == id);
        }
    }
}

Controllers/DetailsTempController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SchadTest.Data;
using SchadTest.Models;

namespace SchadTest.Controllers
{
    public class DetailsTempController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DetailsTempController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: DetailsTemp
        public async Task<IActionResult> Index()
        {
              return View(await _context.DetailsTemp.ToListAsync());
        }

        // GET: DetailsTemp/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.DetailsTemp == null)
            {
                return NotFound();
            }

            var details_Temp = await _context.DetailsTemp
                .FirstOrDefaultAsync(m => m.Id == id);
            if (details_Temp == null)
            {
                return NotFound();
            }

            return View(details_Temp);
        }

        // GET: DetailsTemp/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DetailsTemp/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Header_Guid,Header_Id,ServiceId,Description,Qty,Price,Status,DateAdd")] Details_Temp details_Temp)
        {
            if (ModelState.IsValid)
            {
                _context.Add(details_Temp);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(details_Temp);
        }

        public async Task<IActionResult> AddServices(int intCustomer, string head, int hId, decimal it, decimal to, decimal st)
        {
            if (!string.IsNullOrEmpty(head) && hId > 0 && it > 0 && to > st)
            {

                /*
                Invoice inv = new Invoice();
                inv.CustomerId = intCustomer;
                inv.TotalItbis = it;
                inv.SubTotal = st;
                inv.Total = to;
                if (inv != null)
                {
                    //_context.Add(inv);
                    //await _context.SaveChangesAsync();
                }
                var itemInvoice = _context.Invoice
                   .OrderByDescending(p => p.CustomerId.Equals(intCustomer) && p.TotalItbis.Equals(it) && p.SubTotal.Equals(st) && p.Total.Equals(to))
                   .FirstOrDefault();
                */
                //int qty_ = invoiceDetail.Qty;
                //decimal Price_ = invoiceDetail.Price;
                int IdInvocie = 0;

                Invoice inv = new Invoice();
                inv.CustomerId  = intCustomer;
                inv.TotalItbis  = it;
                inv.SubTotal    = st;
                inv.Total       = to;

                //calculate itbis - subtotal and total


                if (inv != null)
                {
                    _context.Add(inv);
                    await _context.SaveChangesAsync();
                    IdInvocie = inv.Id;
                }

                if (IdInvocie < 0)
                {

                    return NotFound();
                }
                else  {
                    
                var selectServ = (from x in _context.DetailsTemp
                                  join e in _context.Services on x.ServiceId equals e.Id
                                  join t in _context.HeaderTemp on x.Header_Id equals t.Id
                                  where x.Header_Guid.Equals(head) && x.Header_Id.Equals(hId) && x.Status.Equals(true)
                                  select new
                                  {
                                      InvoiceId = IdInvocie,
                                      CustomerId = IdInvocie,
                                      ServiceId = x.ServiceId,
                                      Description = x.Description,
                                      Qty = x.Qty,
                                      Price = x.Price,
                                      PriceDescription = e.PriceDescription,

                                  }).ToList();

                if (selectServ != null)
                {
                        int next = 0;
                    foreach (var item in selectServ)
                    {
                        InvoiceDetail tempSer = new InvoiceDetail();
                        tempSer.InvoiceId = item.InvoiceId;
                        tempSer.CustomerId = item.CustomerId;
                        tempSer.ServiceId = item.ServiceId;
                        tempSer.Description = item.Description;
                        tempSer.Qty = item.Qty;
                        tempSer.Price = item.Price;
                        tempSer.PriceDescription = item.PriceDescription;
                        tempSer.TotalItbis = (item.Price * (0.18M)) * item.Qty;
                        tempSer.SubTotal = (item.Price * item.Qty);
                        tempSer.Total = tempSer.TotalItbis + tempSer.SubTotal;

                        //bool existS = await _context.InvoiceDetail.AnyAsync(x => x.InvoiceId.Equals(item.InvoiceId) && x.CustomerId.Equals(item.CustomerId) && x.ServiceId.Equals(item.ServiceId) && x.Qty.Equals(item.Qty) && x.Price.Equals(item.Price));

                        if (tempSer != null) {
                            _context.Add(tempSer);
                                await _context.SaveChangesAsync();
                            }

                    }
                    
                        
                    Task.Delay(1000);

                            var details_Temp = await _context.HeaderTemp.FirstOrDefaultAsync(d => d.Id.Equals(hId));
                            if (details_Temp != null)
                            {
                                _context.HeaderTemp.Remove(details_Temp);
                            }

                            var details_TempData = await _context.DetailsTemp.Where(d => d.Header_Id.Equals(hId) && d.Header_Guid.Equals(head)).ToListAsync();
                            if (details_TempData != null)
                            {
                                foreach (Details_Temp itemO in details_TempData)
                                {
                                    _context.DetailsTemp.Remove(itemO);
                                }
                                await _context.SaveChangesAsync();

                            }

                            return LocalRedirect($"~/Customers/Index?intCustomer={intCustomer}&hId={hId}");
                        
                }
            }
            }
            return View();
        }

        // GET: DetailsTemp/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.DetailsTemp == null)
            {
                return NotFound();
            }

            var details_Temp = await _context.DetailsTemp.FindAsync(id);
            if (details_Temp == null)
            {
                return NotFound();
            }
            return View(details_Temp);
        }

        // POST: DetailsTemp/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Header_Guid,Header_Id,ServiceId,Description,Qty,Price,Status,DateAdd")] Details_Temp details_Temp)
        {
            if (id != details_Temp.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(details_Temp);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Details_TempExists(details_Temp.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(details_Temp);
        }

        // GET: DetailsTemp/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.DetailsTemp == null)
            {
                return NotFound();
            }

            var details_Temp = await _context.DetailsTemp
                .FirstOrDefaultAsync(m => m.Id == id);
            if (details_Temp == null)
            {
                return NotFound();
            }

            return View(details_Temp);
        }


        // POST: DetailsTemp/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id, int intCustomer, int hId)
        {
            if (_context.DetailsTemp == null)
            {
                return Problem("Entity set 'ApplicationDbContext.DetailsTemp'  is null.");
            }
            var details_Temp = await _context.DetailsTemp.FindAsync(id);
            if (details_Temp != null)
            {
                _context.DetailsTemp.Remove(details_Temp);
            }
            
            await _context.SaveChangesAsync();

Views/Customers/Create.cshtml
@model SchadTest.Models.Customer

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>New Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustName" class="control-label"></label>
                <input asp-for="CustName" class="form-control" />
                <span asp-validation-for="CustName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerTypeId" class="control-label"></label>
                <select asp-for="CustomerTypeId" class ="form-control" asp-items="ViewBag.CustomerTypeId"></select>
                <span class="spanMsg">Choose an option</span>
                <br /><br />
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <i class="fas fa-check-circle text-success"></i>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-outline-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index" class="btn-link"><i class="fas fa-chevron-circle-left"></i> Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Customers/Delete.cshtml
@model SchadTest.Models.Customer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @if (Model.Status == true)
            {
                <i class="fas fa-check-circle text-success"></i>
            }
            else
            {
                <i class="fas fa-times-circle text-danger"></i>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerType.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <br /><br />
        <a asp-action="Index" class="btn-link"><i class="fas fa-chevron-circle-left"></i> Back to List</a>
    </form>
</div>

Views/Customers/Details.cshtml
@model SchadTest.Models.Customer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @if (Model.Status == true)
            {
                <i class="fas fa-check-circle text-success"></i>
            }
            else
            {
                <i class="fas fa-times-circle text-danger"></i>
            }
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CustomerType.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn-link">Edit</a> |
    <a asp-action="Index" class="btn-link"><i class="fas fa-chevron-circle-left"></i> Back to List</a>
</div>

Views/Customers/Edit.cshtml
@model SchadTest.Models.Customer

@{
    ViewData["Title"] = "Edit";
    string st = "Locked";
    string st2 = "Accepted";
    bool st2_ = true;
}

<h1>Edit</h1>

<h4>Customer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="CustName" class="control-label"></label>
                <input asp-for="CustName" class="form-control" />
                <span asp-validation-for="CustName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adress" class="control-label"></label>
                <input asp-for="Adress" class="form-control" />
                <span asp-validation-for="Adress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>

                <select class="form-control form-select" name="Status">
                    @if (Model.Status == true)
                    {
                        <option value="@Model.Status">Accepted</option>
                        <option value="False">Locked</option>

                    }
                    else
                    {
                        <option value="@Model.Status">Locked</option>
                        <option value="True">Accepted</option>

                    }
                </select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerTypeId" class="control-label"></label>
                <select asp-for="CustomerTypeId" class="form-control form-select" asp-items="ViewBag.CustomerTypeId"></select>
                <span asp-validation-for="CustomerTypeId" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index" class="btn-link"><i class="fas fa-chevron-circle-left"></i> Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Customers/Index.cshtml
@model IEnumerable<SchadTest.Models.Customer>

@{
    ViewData["Title"] = "Index";
}

<h1>Customers</h1>

<p>
    <a asp-action="Create" class="btn-link"><i class="far fa-plus-square"></i> Create New</a>
</p>
<table class="table table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CustName)
            </th>

            <th class="text-center">
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CustomerType)
            </th>
            <th><i class="fas fa-pencil-alt"></i> Options</th>
            <th class="text-center"><i class="fas fa-file-invoice-dollar"></i> Invoices</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CustName)
                <br />
                    <p class="addressC"><u>Address:</u> @Html.DisplayFor(modelItem => item.Adress)</p>
            </td>

            <td class="text-center pt-4">
                    @if(item.Status == true)
                    {
                        <i class="fas fa-check-circle text-success"></i>
                    }
                    else{
                    <i class="fas fa-times-circle text-danger"></i>
                    }
            </td>
                <td class="pt-4">
                @Html.DisplayFor(modelItem => item.CustomerType.Description)
            </td>
            <td class="pt-4">
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn-link">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn-link">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn-link">Delete</a>
            </td>

                <td class="pt-4">
                    <div class="row">
                        <div class="col-sm-6">
                            <form asp-action="NewInvoice" asp-controller="DetailsTemp" method="get">
                                <input type="hidden" value="@item.Id" name="intCustomer"/>
                                <button type="submit" class="border-0 btn-link">New Invoice</button>
                            </form>
                        </div>
                        <div class="col-sm-6">
                            <form asp-action="Delete">
                                <input type="hidden" value="@item.Id" />
                                <button type="submit" class="border-0 btn-link">My Invoices</button>
                            </form>
                        </div>
                    </div>
            </td>
        </tr>
}
    </tbody>
</table>